---
abstract: 'Tunnel HTTP methods over GET and POST.'
author:
  - 'JT Smith <jt@plainblack.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-HttpMethodTunnel
requires:
  Plack: 0.9976
resources:
  bugtracker: http://github.com/rizen/Plack-Middleware-HttpMethodTunnel/issues
  repository: git://github.com/rizen/Plack-Middleware-HttpMethodTunnel.git
version: 0.0100
